Vagrant.configure("2") do |config|

  # Windows configuration
  config.vm.define "dotfiles-windows" do |windows|
    windows.vm.box = "gusztavvargadr/windows-11"
    
    windows.vm.boot_timeout = 1500 

    windows.vm.synced_folder "..", "/Users/vagrant/.local/share/chezmoi", type: "virtualbox"

    windows.vm.provision "shell",
      privileged: true,
#       path: "run-tests.ps1",
      env: {
        "VAGRANT" => "1"
      }

    windows.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4       

      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end

  # Linux configuration
  config.vm.define "dotfiles-linux" do |linux|
    linux.vm.box = "ubuntu/jammy64"
  
    linux.vm.synced_folder "..", "/home/vagrant/.local/share/chezmoi", type: "virtualbox"
  
    linux.vm.provision "shell", 
        path: "run-tests.sh",
        env: {
          "VAGRANT" => "1"
        }
  
    linux.vm.provider "virtualbox" do |vb|
      vb.memory = 8192         
      vb.cpus = 4              
  
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end
end
