Vagrant.configure("2") do |config|

  # Windows configuration
  config.vm.define "dotfiles-windows" do |windows|
    windows.vm.box = "gusztavvargadr/windows-11"
    
    windows.vm.boot_timeout = 2000
    windows.winrm.timeout = 2000
    windows.winrm.retry_delay = 30

    windows.vm.synced_folder "..", "/Users/vagrant/.local/share/chezmoi", type: "virtualbox"

    windows.vm.provider "virtualbox" do |v|
      v.memory = 8192
      v.cpus = 4

      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end

  # Linux configuration
  config.vm.define "dotfiles-linux" do |linux|
    linux.vm.box = "ubuntu/jammy64"
  
    linux.vm.synced_folder "..", "/home/vagrant/.local/share/chezmoi", type: "virtualbox"
        
    linux.vm.provider "virtualbox" do |v|
      v.memory = 8192         
      v.cpus = 4              
  
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end
end
